### PR TITLE
CI and Build Script

### LINKED ISSUE #9: CI Server for nunit-project-editor
Build and test on each commit.

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Fixes #9.

Also includes a few path changes which were brought up by running the tests from a different location.

CHANGES.txt is predominantly a placeholder for now!

### CODE REVIEW

**Comment by CharliePoole** [comment]
Issues...

1. The Appveyor build seems not to be using the generated file suffix to publish packages.

2. We don't normally package with the travis build

3. The travis build has some test failures that are unrelated to the script, but others are related - they can't be run on travis because they require a display.

**Comment by ChrisMaddock** [comment]
D'oh - more worryingly, I wasn't throwing an exception to fail the build on test failure. :-/ Will sort that tomorrow - presume we're better just not running the tests on Unix than trying to categorize them. (That said, is there even a need to build it?)

> The Appveyor build seems not to be using the generated file suffix to publish packages.

Think I see what you mean on the GUI repo, didn't realise we did that. Will add it in.

**Comment by CharliePoole** [comment]
It would be OK to temporarily disable the tests on Travis but in the long run we need to build and test there. Debian and most of its derivatives only package software that they can build from source. So we have to build on Linux. We could skip testing, but only if we don't care whether it works. :-)

**Comment by ChrisMaddock** [comment]
Ok, sure. Will dig in to it! :-)

**Comment by ChrisMaddock** [comment]
Ok, the changes here should fix most issues. (I've also checked that failed tests actually fails the build this time - whoops!)

The failures on Unix (once the GUI stuff were in) were due to `Path.AltDirectorySeparatorChar` being a forward slash on mono - contrary to what [MSDN states](https://msdn.microsoft.com/en-us/library/system.io.path.altdirectoryseparatorchar(v=vs.110).aspx). Looking at the code, it seems the path resolution stuff is intended for resolution of paths generated within the program, rather than files transferred between OS's, so adapting the code didn't seem the right solution. I instead excluded the tests with Windows paths on Unix, to match what was already done for `RelativePathTest`.

This is ready for review again.

**Comment by ericnewton76** [comment]
So I see you're using AppVeyor but I'm confused as to where the appveyor project is (ie the url to see latest builds)

**Comment by CharliePoole** [comment]
See https://ci.appveyor.com/project/CharliePoole/nunit-project-editor

**Pull request merged**
